### model
model_name_or_path: meta-llama/Meta-Llama-3-8B

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: Tem-DocRED-train
template: default
cutoff_len: 1024
max_samples: 3000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3-8b/lora/sft
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_steps: 20
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 1000